spring.datasource:
  url: jdbc:h2:mem:test
  user: sa
  password: sa
logging.level:
  jdbc: OFF
  jdbc.sqltiming: DEBUG
  org.springframework.security.web: DEBUG
spring.jpa.hibernate.ddl-auto: validate
